# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

#                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# Find the sum of all the even-valued terms in the sequence which do not exceed
# four million.

stime = Time.now.to_f
sum = 2
first = 1
second = 2
while second <= 4000000 do
  potential = first + second
  if ((potential) % 2 == 0)
    sum += potential
  end
  first = second
  second = potential
end
ftime = Time.now.to_f
puts sum.to_s + " computed in " + (ftime - stime).to_s + " sec."
